apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: karsa-redis
  namespace: karsa-pantau
  labels:
    app: karsa-redis
spec:
  serviceName: karsa-redis-svc
  replicas: 1
  selector:
    matchLabels:
      app: karsa-redis
  template:
    metadata:
      labels:
        app: karsa-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command:
            - redis-server
            - --appendonly
            - "yes"
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: karsa-redis-svc
  namespace: karsa-pantau
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: karsa-redis
